"""empty message

Revision ID: initial_revision
Revises: 
Create Date: 2022-09-30 00:46:40.565202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial_revision'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_history',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('avatar_ext', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'timestamp')
    )
    op.create_table('emojis',
    sa.Column('emoji_id', sa.BigInteger(), nullable=True),
    sa.Column('emoji_unicode', sa.Unicode(length=7), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.UniqueConstraint('emoji_id', 'emoji_unicode', name='uq_emoji')
    )
    op.create_table('nickname_history',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('nickname', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'timestamp')
    )
    op.create_table('username_history',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('username', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'timestamp')
    )
    op.create_table('users',
    sa.Column('int_user_id', sa.BigInteger(), nullable=False),
    sa.Column('real_user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('discriminator', sa.SmallInteger(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('int_user_id')
    )
    op.create_table('guilds',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('int_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('voice_region', sa.Enum('us_west', 'us_east', 'us_south', 'us_central', 'eu_west', 'eu_central', 'singapore', 'london', 'sydney', 'amsterdam', 'frankfurt', 'brazil', 'hongkong', 'russia', 'japan', 'southafrica', 'south_korea', 'india', 'europe', 'dubai', 'vip_us_east', 'vip_us_west', 'vip_amsterdam', name='voiceregion'), nullable=True),
    sa.Column('afk_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('afk_timeout', sa.Integer(), nullable=True),
    sa.Column('mfa', sa.Boolean(), nullable=True),
    sa.Column('verification_level', sa.Enum('none', 'low', 'medium', 'high', 'table_flip', 'extreme', 'double_table_flip', 'very_high', name='verificationlevel'), nullable=True),
    sa.Column('explicit_content_filter', sa.Enum('disabled', 'no_role', 'all_members', name='contentfilter'), nullable=True),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('splash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['int_owner_id'], ['users.int_user_id'], ),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('audit_log',
    sa.Column('audit_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Enum('guild_update', 'channel_create', 'channel_update', 'channel_delete', 'overwrite_create', 'overwrite_update', 'overwrite_delete', 'kick', 'member_prune', 'ban', 'unban', 'member_update', 'member_role_update', 'member_move', 'member_disconnect', 'bot_add', 'role_create', 'role_update', 'role_delete', 'invite_create', 'invite_update', 'invite_delete', 'webhook_create', 'webhook_update', 'webhook_delete', 'emoji_create', 'emoji_update', 'emoji_delete', 'message_delete', 'message_bulk_delete', 'message_pin', 'message_unpin', 'integration_create', 'integration_update', 'integration_delete', name='auditlogaction'), nullable=True),
    sa.Column('int_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Unicode(), nullable=True),
    sa.Column('category', sa.Enum('create', 'delete', 'update', name='auditlogactioncategory'), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['int_user_id'], ['users.int_user_id'], ),
    sa.PrimaryKeyConstraint('audit_entry_id'),
    sa.UniqueConstraint('audit_entry_id', 'guild_id', name='uq_audit_log')
    )
    op.create_table('audit_log_crawl',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('last_audit_entry_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('channel_categories',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_nsfw', sa.Boolean(), nullable=True),
    sa.Column('changed_roles', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('parent_category_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['channel_categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('guild_membership',
    sa.Column('int_user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('nick', sa.Unicode(length=32), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['int_user_id'], ['users.int_user_id'], ),
    sa.PrimaryKeyConstraint('int_user_id', 'guild_id'),
    sa.UniqueConstraint('int_user_id', 'guild_id', name='uq_guild_membership')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('raw_permissions', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('is_hoisted', sa.Boolean(), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=True),
    sa.Column('is_mentionable', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_nsfw', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('topic', sa.UnicodeText(), nullable=True),
    sa.Column('changed_roles', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['channel_categories.category_id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('role_membership',
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('int_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['int_user_id'], ['users.int_user_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.UniqueConstraint('role_id', 'int_user_id', name='uq_role_membership')
    )
    op.create_table('voice_channels',
    sa.Column('voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('user_limit', sa.SmallInteger(), nullable=True),
    sa.Column('changed_roles', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['channel_categories.category_id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('voice_channel_id')
    )
    op.create_table('channel_crawl',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('message_type', sa.Enum('default', 'recipient_add', 'recipient_remove', 'call', 'channel_name_change', 'channel_icon_change', 'pins_add', 'new_member', 'premium_guild_subscription', 'premium_guild_tier_1', 'premium_guild_tier_2', 'premium_guild_tier_3', 'channel_follow_add', name='messagetype'), nullable=True),
    sa.Column('system_content', sa.UnicodeText(), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('embeds', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.SmallInteger(), nullable=True),
    sa.Column('webhook_id', sa.BigInteger(), nullable=True),
    sa.Column('int_user_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('reactions',
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('emoji_id', sa.BigInteger(), nullable=True),
    sa.Column('emoji_unicode', sa.Unicode(length=7), nullable=True),
    sa.Column('int_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['int_user_id'], ['users.int_user_id'], ),
    sa.UniqueConstraint('message_id', 'emoji_id', 'emoji_unicode', 'int_user_id', 'created_at', name='uq_reactions')
    )
    op.create_table('typing',
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('int_user_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['int_user_id'], ['users.int_user_id'], ),
    sa.UniqueConstraint('timestamp', 'int_user_id', 'channel_id', 'guild_id', name='uq_typing')
    )
    op.create_table('mentions',
    sa.Column('mentioned_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('USER', 'ROLE', 'CHANNEL', name='mentiontype'), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('mentioned_id', 'type', 'message_id'),
    sa.UniqueConstraint('mentioned_id', 'type', 'message_id', name='uq_mention')
    )
    op.create_table('pins',
    sa.Column('pin_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('pinner_id', sa.BigInteger(), nullable=True),
    sa.Column('int_user_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['int_user_id'], ['users.int_user_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['pinner_id'], ['users.int_user_id'], ),
    sa.PrimaryKeyConstraint('pin_id', 'message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pins')
    op.drop_table('mentions')
    op.drop_table('typing')
    op.drop_table('reactions')
    op.drop_table('messages')
    op.drop_table('channel_crawl')
    op.drop_table('voice_channels')
    op.drop_table('role_membership')
    op.drop_table('channels')
    op.drop_table('roles')
    op.drop_table('guild_membership')
    op.drop_table('channel_categories')
    op.drop_table('audit_log_crawl')
    op.drop_table('audit_log')
    op.drop_table('guilds')
    op.drop_table('users')
    op.drop_table('username_history')
    op.drop_table('nickname_history')
    op.drop_table('emojis')
    op.drop_table('avatar_history')
    # ### end Alembic commands ###
